name: 'build-test'
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn tsc --noEmit
      - run: yarn lint
        # - run: yarn test currently breaks on 0.64
        env:
          CI: true
