name: Visual Regression Tests - iOS

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  run-visual-regression-ios:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Get Runner Information
        run: /usr/bin/xcodebuild -version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install CocoaPods
        run: gem install cocoapods -v 1.11.0

      - uses: actions/cache@v2
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        run: pod install
        working-directory: ./ios

      - name: 'Create env file'
        run: |
          touch .env
          echo redirect_url=${{ secrets.REDIRECT_URL }} >> .env
          echo client_secret=${{ secrets.CLIENT_SECRET }} >> .env
          echo client_id=${{ secrets.CLIENT_ID }} >> .env
          echo revenuecat_key=${{ secrets.REVENUECAT_KEY }} >> .env
          cat .env

      - name: Run rnuc
        run: yarn env

      - uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 13 Pro'
          os_version: '>=15.0'

      - name: Run Owl Build
        run: yarn owl:build:ios

      - name: Run Owl Test
        run: yarn owl:test:ios

      - name: Store screenshots and report as artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: owl-results
          path: ./.owl
